/** This file was autogenerated by the mpc_planner_solver package at 11:21AM on September 05, 2025*/
#ifndef __MPC_PLANNER_PARAMETERS_H__
#define __MPC_PLANNER_PARAMETERS_H__

namespace MPCPlanner{

struct AcadosParameters;
void setSolverParameterAcceleration(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterAngularVelocity(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterVelocity(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterReferenceVelocity(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterContour(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterLag(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterTerminalAngle(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterTerminalContouring(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterSplineXA(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineXB(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineXC(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineXD(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineYA(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineYB(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineYC(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineYD(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterSplineStart(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterEgoDiscOffset(int k, AcadosParameters& params, const double value, int index=0);
void setSolverParameterDecompA1(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterDecompA2(int k, AcadosParameters& params, const double value, int index);
void setSolverParameterDecompB(int k, AcadosParameters& params, const double value, int index);
}
#endif