acceleration: 0
angular_velocity: 1
contour: 4
disc_0_decomp_0_a1: 81
disc_0_decomp_0_a2: 82
disc_0_decomp_0_b: 83
disc_0_decomp_10_a1: 111
disc_0_decomp_10_a2: 112
disc_0_decomp_10_b: 113
disc_0_decomp_11_a1: 114
disc_0_decomp_11_a2: 115
disc_0_decomp_11_b: 116
disc_0_decomp_1_a1: 84
disc_0_decomp_1_a2: 85
disc_0_decomp_1_b: 86
disc_0_decomp_2_a1: 87
disc_0_decomp_2_a2: 88
disc_0_decomp_2_b: 89
disc_0_decomp_3_a1: 90
disc_0_decomp_3_a2: 91
disc_0_decomp_3_b: 92
disc_0_decomp_4_a1: 93
disc_0_decomp_4_a2: 94
disc_0_decomp_4_b: 95
disc_0_decomp_5_a1: 96
disc_0_decomp_5_a2: 97
disc_0_decomp_5_b: 98
disc_0_decomp_6_a1: 99
disc_0_decomp_6_a2: 100
disc_0_decomp_6_b: 101
disc_0_decomp_7_a1: 102
disc_0_decomp_7_a2: 103
disc_0_decomp_7_b: 104
disc_0_decomp_8_a1: 105
disc_0_decomp_8_a2: 106
disc_0_decomp_8_b: 107
disc_0_decomp_9_a1: 108
disc_0_decomp_9_a2: 109
disc_0_decomp_9_b: 110
ego_disc_0_offset: 80
lag: 5
num parameters: 117
reference_velocity: 3
spline0_start: 16
spline1_start: 25
spline2_start: 34
spline3_start: 43
spline4_start: 52
spline5_start: 61
spline6_start: 70
spline7_start: 79
spline_x0_a: 8
spline_x0_b: 9
spline_x0_c: 10
spline_x0_d: 11
spline_x1_a: 17
spline_x1_b: 18
spline_x1_c: 19
spline_x1_d: 20
spline_x2_a: 26
spline_x2_b: 27
spline_x2_c: 28
spline_x2_d: 29
spline_x3_a: 35
spline_x3_b: 36
spline_x3_c: 37
spline_x3_d: 38
spline_x4_a: 44
spline_x4_b: 45
spline_x4_c: 46
spline_x4_d: 47
spline_x5_a: 53
spline_x5_b: 54
spline_x5_c: 55
spline_x5_d: 56
spline_x6_a: 62
spline_x6_b: 63
spline_x6_c: 64
spline_x6_d: 65
spline_x7_a: 71
spline_x7_b: 72
spline_x7_c: 73
spline_x7_d: 74
spline_y0_a: 12
spline_y0_b: 13
spline_y0_c: 14
spline_y0_d: 15
spline_y1_a: 21
spline_y1_b: 22
spline_y1_c: 23
spline_y1_d: 24
spline_y2_a: 30
spline_y2_b: 31
spline_y2_c: 32
spline_y2_d: 33
spline_y3_a: 39
spline_y3_b: 40
spline_y3_c: 41
spline_y3_d: 42
spline_y4_a: 48
spline_y4_b: 49
spline_y4_c: 50
spline_y4_d: 51
spline_y5_a: 57
spline_y5_b: 58
spline_y5_c: 59
spline_y5_d: 60
spline_y6_a: 66
spline_y6_b: 67
spline_y6_c: 68
spline_y6_d: 69
spline_y7_a: 75
spline_y7_b: 76
spline_y7_c: 77
spline_y7_d: 78
terminal_angle: 6
terminal_contouring: 7
velocity: 2
